### ISSUE TITLE
Make error msg data attr more flexibel in validate method

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-validator#1]
change msg = $(this).attr('data-errormessage-name');
to msg = $(this).attr('data-errormessage-' + validationType);

**Comment by ain** [comment]
I also think we can go also with 

``` js
$(this).data('errormessage-' + validationType)
```

since we shouldn't support ancient jQuery versions anyway, or?

**Comment by GeorgMeyer23** [comment]
@ain nice call.

**Comment by davleh** [comment]
Done.
