### ISSUE TITLE
Support for custom validation schemas

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-validator#12]
One should be able to define custom validation schemas, e.g. pass them in on component init.

**Comment by davleh** [comment]
@ain This should definitely be the next enhancement to be implemented!

**Comment by ain** [comment]
Yeah, I could see the clear use-case for it as well, already back in the days.

**Comment by ain** [comment]
`regexp` validation schema can be used for custom validations.

Delivered by @davleh in f5cd4e5e. Documentation landing in #23.
