### ISSUE TITLE
Extend error handling to field label

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-validator#15]
Validator should be able to toggle error class on the label according to the field.
Maybe optional by parameter.

@ain what do you think? We have that requirement on a project...

**Comment by ain** [comment]
Yes, it's also the default behaviour in many other frameworks (Rails/Symfony etc.) that the errored fields are being wrapped incl. the label. Our current behaviour has a lot to do with GFX almost always defining a sort of exceptional behaviour that differs from standard approaches.

Could be an option that either wraps or assigns error class exclusively on the field, providing a way to toggle. Correct me if I misunderstood you.

**Comment by davleh** [comment]
I would select the label by reading the id of the input and searching the label(s) with according for attribute and then add an error class to those label. Would that be ok? Or does anyone have a better idea?

**Comment by ain** [comment]
It'd definitely be the easiest, but not necessarily the best option. 

label and a field may not be the only elements that need to know about their erroneous status. Think of special controls, e.g. a date control combining 3 selects with 3 labels.

**Comment by davleh** [comment]
Ok, then what about using data-connected-validator-field="id" or something like this? And then searching for all elements with that data attribute holding the id of the input?

**Comment by ain** [comment]
@davleh I think it's an excellent idea. Instead of expecting ID, I'd expect (any) selector incl. selector chain. Probably that's how you meant it. 

Also, I'd go with better naming. `data-validator-connect` could also imply validation targets so I'd suggest `data-validator-error-connect` or `data-validator-error-subscribers`.

**Comment by davleh** [comment]
Ok, I meant it the other way round I think... I adjusted the naming to data-connected-validator-field="id" as the input should always have a unique id. Then I could simply read the field id and select all elements with a data attribute holding this id.
But I also like your idea and the naming data-validation-error-class-subscribers!
