### ISSUE TITLE
data-errormsg is inappropriate

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-validator#28]
Starting a discussion Re `data-errormsg` attribute which IMO is inappropriate. 

It's used to display validation error message as per field. Every other data attribute (see [Usage](https://github.com/interactive-pioneers/iptools-jquery-validator#usage)) is namespaced with `data-validation` exc. for error message.

Calling to refactor this to `data-validation-errormsg-<schema>`.  Since we're working against `2.0.0` release, it'd be a breaking change and thus good opportunity to do it now.

Objections?

**Comment by ain** [comment]
Thanks @GeorgMeyer23. Others?

**Comment by ain** [comment]
Thanks @mpeters1. Democracy won, it's a task.

**Comment by davleh** [comment]
Sorry for late participation. No objections, you are absolutely right!
