### ISSUE TITLE
Implement event listeners

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-validator#4]
Should we implement at least an event listener that fires 'validation' on form submit?

Add an option where validation of a single field happens on change?

**Comment by ain** [comment]
:+1:

**Comment by GeorgMeyer23** [comment]
- Add optional trigger validator for form fields on form submit.
- Add optional trigger validator for single field on change.

**Comment by davleh** [comment]
Done.
